services:
  docs:
    image: saas_local_docs
    container_name: saas_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./saas:/app/saas:z
    ports:
      - '9000:9000'
    command: /start-docs
